image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
    - build
    - test

build:
    stage: build
    script:
        - dotnet build
    artifacts:
        paths:
            - "*/bin"
        expire_in: 2 week

build-image:
    stage: build
    services:
        - docker:dind
    image: docker
    script:
        # - docker build -t dashboard-api -f .\Dashboard.Api\Dockerfile .
        # - docker build -t dashboard-admin-api -f .\Dashboard.Admin.Api\Dockerfile .
        - docker-compose up
    artifacts:
        expire_in: 2 week

test:
    stage: test
    script: 
        - "dotnet test"